# Generated by Django 3.0.7 on 2020-06-21 05:18

import core.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('folder', models.CharField(blank=True, max_length=255, null=True)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('day_hours', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=core.models.get_default_day_hours, size=None)),
                ('day_bwlimit', models.PositiveIntegerField(default=200)),
                ('night_bwlimit', models.PositiveIntegerField(default=800)),
                ('limit_during_day', models.BooleanField(default=True)),
                ('limit_during_night', models.BooleanField(default=True)),
                ('agentid', models.CharField(blank=True, max_length=255, null=True)),
                ('backup_schedule', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('offsite_managed', models.BooleanField(default=True)),
                ('offsites_enabled', models.BooleanField(default=True)),
                ('backups_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('folder', models.CharField(blank=True, max_length=255, null=True)),
                ('salt_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sambashare', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OffsiteJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('logfile_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='running', max_length=100)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offsitejobs', to='core.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('backup', 'Incremental'), ('activefull', 'Active Full'), ('standalone', 'Standalone Full')], default='backup', max_length=255)),
                ('proc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cmdline', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='running', max_length=100)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backupjobs', to='core.Agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='core.Client'),
        ),
    ]
